### ISSUE TITLE
Can't omit metadata with @with_kw

### ISSUE THREAD

**Issue by fredcallaway** [rafaqz/FieldMetadata.jl#17]
Example:
```julia
using Parameters
using FieldMetadata: @bounds
@bounds @with_kw struct Broken
    a::Real = 1
    b::Real = 2 | (0, Inf)
end
```

If I take off the `= 1`, it's fine.

**Comment by rafaqz** [comment]
Yeah ommitting isnt easy with multiple things. Also because the architecture is v different to parameters.jl. 

Just put an underscore in to get the default.

Also maybe check out ModelParameters.jl, its a different way of adding metadata without some of these problems.

**Comment by fredcallaway** [comment]
Thanks!

**Comment by fredcallaway** [comment]
(It might be worth adding a note on this in the readme to save other people my debugging adventure)

**Comment by rafaqz** [comment]
Go for it :D
